// Shared TypeScript types for ally-agent-room frontend
// These types match the backend's event model exactly

// Agent identity
export type AgentId = 'ba' | 'dev-lead' | 'dev-be' | 'dev-fe' | 'tester' | 'devops';

// Agent visual/activity state
export type AgentState = 'idle' | 'working' | 'wandering' | 'delivering' | 'waiting' | 'error';

// Token usage from Claude CLI stream-json
export type TokenUsage = {
  input_tokens: number;
  output_tokens: number;
};

// Session information
export type SessionInfo = {
  id: string;
  name: string;
  status: 'active' | 'idle' | 'stopped';
  createdAt: string;
  agentCount: number;
  claudeSessionId?: string;
};

// Beads task from bd CLI
export type BeadsTask = {
  id: string;
  title: string;
  status: 'backlog' | 'ready' | 'in-progress' | 'done' | 'blocked';
  priority: 'P1' | 'P2' | 'P3' | 'P4';
  agent?: AgentId;
  epic?: string;
  description?: string;
  dependencies?: string[];
  blockedBy?: string[];
};

// Chat message between user and agents
export type ChatMessage = {
  id: string;
  from: AgentId | 'user';
  to: AgentId | 'user' | 'assistant';
  content: string;
  timestamp: string;
  streaming: boolean;
  permissionRequest?: PermissionRequest;
};

// Tool use permission request from an agent
export type PermissionRequest = {
  id: string;
  agent: AgentId;
  tool: string;
  input: Record<string, unknown>;
};

// File diff entry generated by an agent
export type DiffEntry = {
  id: string;
  agent: AgentId;
  file: string;
  diff: string;
  timestamp: string;
};

// Timeline event entry for the activity stream
export type TimelineEntry = {
  id: string;
  agent: AgentId;
  action: string;
  type: 'chat' | 'tool_use' | 'task_claim' | 'task_complete' | 'error' | 'state_change';
  detail?: string;
  timestamp: string;
};

// Agent metadata (display info, positioning)
export type AgentInfo = {
  id: AgentId;
  name: string;
  model: string;
  color: string;
  deskPosition: [number, number];
};

// WebSocket event discriminated union
// All real-time events from the backend flow through this type
export type WSEvent =
  | {
      type: 'agent_state_change';
      agent: AgentId;
      state: AgentState;
      detail?: string;
    }
  | {
      type: 'chat_message';
      from: AgentId | 'user';
      to: AgentId | 'user';
      content: string;
      streaming: boolean;
    }
  | {
      type: 'tool_use';
      agent: AgentId;
      tool: string;
      input: Record<string, unknown>;
      status: 'pending' | 'approved' | 'denied';
    }
  | {
      type: 'permission_request';
      id: string;
      agent: AgentId;
      tool: string;
      input: Record<string, unknown>;
    }
  | {
      type: 'task_update';
      tasks: BeadsTask[];
    }
  | {
      type: 'cost_update';
      agent: AgentId;
      tokens: TokenUsage;
      cost: number;
    }
  | {
      type: 'diff_event';
      agent: AgentId;
      file: string;
      diff: string;
    }
  | {
      type: 'timeline_event';
      agent: AgentId;
      action: string;
      timestamp: string;
      detail?: string;
    }
  | {
      type: 'session_update';
      sessions: SessionInfo[];
    }
  | {
      type: 'error';
      agent?: AgentId;
      message: string;
    }
  | {
      type: 'notification';
      title: string;
      body: string;
      level: 'info' | 'warning' | 'error';
    };
